### ISSUE TITLE
meta http port config

### ISSUE THREAD

**Issue by mrichar1** [salt-formulas/salt-formula-influxdb#30]
I've been trying to alter the `meta` settings according to the docs by doing:

```
influxdb:
  meta:
    enabled:true
    bind:
      address: 127.0.0.1
      port: 8088
      http_address: 127.0.0.1
      http_port: 8091
```

However this continually returns the error:

> SaltRenderError: Jinja variable 'dict object' has no attribute 'http_port'

Looking at the `influxdb.conf` jinja template, it appears to do:

```
bind-address = "{{ server.meta.bind.address }}:{{ server.admin.bind.port }}"
http-bind-address = "{{ server.meta.bind.http_address }}:{{ server.admin.bind.http_port }}"
```

Shouldn't the port for these 2 config options be read from `server.meta.` and not `server.admin.` ?

https://github.com/salt-formulas/salt-formula-influxdb/blob/a7b4635c0ae91700f6d3935df2fe5336b0e6a2f2/influxdb/files/influxdb.conf#L43
